# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: required
dist: trusty 

os:
  - linux
 
#  - osx

julia:
  - 0.4.3

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    #  - sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get install cmake mpich
  - sudo apt-get update -q
  - sudo apt-get install -y gcc gfortran cmake openmpi-bin openmpi-common libopenmpi-dev
  - julia -e 'Pkg.add("ParallelAccelerator")'
  - julia -e 'Pkg.add("MPI")'
  - julia -e 'Pkg.clone("https://github.com/IntelLabs/HPAT.jl"); Pkg.build("HPAT"); Pkg.test("HPAT")'
  - mpirun -np 2 julia examples/pi.jl
