# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: required
dist: trusty 

os:
  - linux
 
#  - osx

julia:
  - 0.4.5

notifications:
  email: false

env:
    - PROSPECT_DEV_MODE=1

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    #  - sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get install cmake mpich
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc g++ gfortran cmake openmpi-bin openmpi-common libopenmpi-dev libhdf5-openmpi-dev libblas-dev libopenblas-dev 
  - julia -e 'Pkg.clone("CompilerTools")'
  - julia -e 'Pkg.clone("ParallelAccelerator")'
  - julia -e 'Pkg.build("ParallelAccelerator")'
    #  - julia -e 'Pkg.clone(pwd()); Pkg.build("HPAT"); Pkg.test("HPAT")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("HPAT"); Pkg.test("HPAT")'
  - julia examples/pi.jl 
  - mpirun -np 2 julia examples/pi.jl 
  - julia generate_data/generate_logistic_regression.jl --instances=10000 --path=/tmp/
  - mpirun -np 2 julia examples/logistic_regression.jl --iterations=10 --file=/tmp/logistic_regression.hdf5
